CREATE TABLE "CONTINUUMADM"."USERS"
(
  "USERNAME" VARCHAR2(50 BYTE)  NOT NULL ENABLE,
  "PASSWORD" VARCHAR2(500 BYTE) NOT NULL ENABLE,
  "ENABLED"  NUMBER(1, 0)       NOT NULL ENABLE,
  PRIMARY KEY ("USERNAME") ENABLE
);
/
CREATE TABLE "CONTINUUMADM"."AUTHORITIES"
(
  "USERNAME"  VARCHAR2(50 BYTE) NOT NULL ENABLE,
  "AUTHORITY" VARCHAR2(50 BYTE) NOT NULL ENABLE,
  CONSTRAINT "FK_AUTHORITIES_USERS" FOREIGN KEY ("USERNAME")
  REFERENCES "CONTINUUMADM"."USERS" ("USERNAME") ENABLE
);
/
CREATE UNIQUE INDEX "CONTINUUMADM"."IX_AUTH_USERNAME" ON "CONTINUUMADM"."AUTHORITIES" ("USERNAME", "AUTHORITY");
/
CREATE TABLE "CONTINUUMADM"."MESSAGE"
(
  "ID"            CHAR(36 BYTE)      NOT NULL ENABLE,
  "HEADERS"       CLOB               NOT NULL ENABLE,
  "PAYLOAD_CLASS" VARCHAR2(100 BYTE) NOT NULL ENABLE,
  "PAYLOAD"       CLOB               NOT NULL ENABLE,
  "TIMESTAMP"     TIMESTAMP(6)       NOT NULL ENABLE,
  PRIMARY KEY ("ID")
);
/
CREATE TABLE "CONTINUUMADM"."MESSAGE_RECEIPT"
(
  "SERVER_NODE_IDENTIFIER" VARCHAR2(50 BYTE) NOT NULL ENABLE,
  "MESSAGE_ID"             CHAR(36 BYTE)     NOT NULL ENABLE,
  PRIMARY KEY ("MESSAGE_ID", "SERVER_NODE_IDENTIFIER")
);
/
CREATE TABLE "CONTINUUMADM"."PATIENT"
(
  "ID"                     NUMBER(19, 0)      NOT NULL ENABLE,
  "ID_ASSIGNING_AUTHORITY" VARCHAR2(100 CHAR) NOT NULL ENABLE,
  "BODY"                   CLOB,
  "DOB"                    DATE,
  "GENDER"                 VARCHAR2(30 CHAR),
  "FAMILY"                 VARCHAR2(30 CHAR),
  "GIVEN"                  VARCHAR2(30 CHAR),
  "SUFFIX"                 VARCHAR2(10 CHAR),
  "PATIENT_ID"             VARCHAR2(30 CHAR),
  "NAME"                   VARCHAR2(100 BYTE),
  "CREATED"                TIMESTAMP(6)       NOT NULL ENABLE,
  "RAW_MESSAGE"            CLOB,
  PRIMARY KEY ("ID") ENABLE
);