DROP TABLE "CONTINUUMADM"."AUTHORITIES"
/

DROP TABLE "CONTINUUMADM"."USERS"
/

DROP TABLE "CONTINUUMADM"."MESSAGE"
/

DROP TABLE "CONTINUUMADM"."MESSAGE_RECEIPT"
/

DROP TABLE "CONTINUUMADM"."PATIENT"
/

DROP TABLE "CONTINUUMADM".RAW_MESSAGE
/